### ISSUE TITLE
line weight not working properly if weight is a function

### ISSUE THREAD

**Issue by tim-salabim** [robertleeplummerjr/Leaflet.glify#44] opened 2020-01-26 09:42 UTC
Hi @robertleeplummerjr 

I tested the new lines features. While the patch to prevent drawing multiple lines beyond zoom 18 works fine, I run into issues when I try to pass a function to `weight`.

The following are screenshots made for 2 linesstrings with weights being an `Array(4, 10)`:

1. with normal leaflet (i.e. `L.polyline`):

![Screenshot from 2020-01-26 10-35-54](https://user-images.githubusercontent.com/2826432/73133374-13022a80-4028-11ea-93fe-682dff62bc67.png)

2. with Leaflet.glify (i.e. `L.glify.lines`):

![Screenshot from 2020-01-26 10-36-20](https://user-images.githubusercontent.com/2826432/73133395-4d6bc780-4028-11ea-992c-46f4f86a2bd2.png)

Obviously, the result is not quite correct, which is also reflected by the fact that I see the following warnings in the browser console:

![Screenshot from 2020-01-26 10-36-52](https://user-images.githubusercontent.com/2826432/73133412-7b510c00-4028-11ea-896b-96b0e20758d3.png)

So there seems to be an issue in glify.js line 21395:13

The function I am supplying to `weight` in case of mulitple weights is

```js
function(index, feature) { return weight[index]; };
```
where `weight` is the above mentioned array.

Any ideas?

**Comment by robertleeplummerjr** [comment] 2020-01-26 20:04
Can you supply the code to reproduce this, or have a link to it?

**Comment by tim-salabim** [comment] 2020-01-27 09:06
Is the html of any use?

**Comment by robertleeplummerjr** [comment] 2020-01-27 11:39
That'd be most helpful.  In particular the geojson.

**Comment by tim-salabim** [comment] 2020-01-27 11:41
Ok, I'll send it later. Currently at work

**Comment by tim-salabim** [comment] 2020-01-27 17:00
[lines_width_test.zip](https://github.com/robertleeplummerjr/Leaflet.glify/files/4118258/lines_width_test.zip)

**Comment by njadid** [comment] 2020-02-11 15:23
I can draw lines with glify with different line widths. I tested the code provided by @tim-salabim and here is the screenshot. I used line-width branch.
![image](https://user-images.githubusercontent.com/20304972/74249383-af762f00-4cae-11ea-81b7-d8e4eacbba50.png)

However, glify is slow in adding weight to lines in case of larger number of features. In my case, I am looking at 100,000 lines (river network) that have at least 3 vertices.

It could be faster. I am looking at lines (21379:21400)
```
else if (typeof weight === 'function') {
      var vertexCount = 0;
      var features = this.settings.data.features;

      for (var i = 0; i < this.verts.length; i++) {
        var vert = this.verts[i];
        var weightValue = weight(i, features[i]); // Now draw the lines several times, but like a brush, taking advantage of the half pixel line generally used by cards

        for (var _yOffset = -weightValue; _yOffset < weightValue; _yOffset += 0.5) {
          for (var _xOffset = -weightValue; _xOffset < weightValue; _xOffset += 0.5) {
            // -- set base matrix to translate canvas pixel coordinates -> webgl coordinates
            mapMatrix.set(pixelsToWebGLMatrix).scaleMatrix(scale).translateMatrix(-offset.x + _xOffset / scale, -offset.y + _yOffset / scale);
            gl.viewport(0, 0, canvas.width, canvas.height);
            gl.vertexAttrib1f(gl.aPointSize, pointSize); // -- attach matrix value to 'mapMatrix' uniform in shader

            gl.uniformMatrix4fv(this.matrix, false, mapMatrix);
            gl.drawArrays(gl.LINES, vertexCount / 5, (vertexCount + vert.length) / 5);
          }
        }

        vertexCount += vert.length * 2 - 10; // number of vertexes is features.length * 2, but not first or last (5 each) in array of each set of features
      }
```

**Comment by robertleeplummerjr** [comment] 2020-02-22 22:49
Just pushed fixes.  Please try again and let me know, this should be resolved.

**Comment by njadid** [comment] 2020-02-23 02:26
![image](https://user-images.githubusercontent.com/20304972/75102456-83618480-55b1-11ea-8871-0a8d231c65dd.png)
Works great!
Should the opacity be also variable? or could it be passed to color in the function as rgba?

**Comment by tim-salabim** [comment] 2020-02-23 10:55
This works beautifully now! 

![Screenshot from 2020-02-23 11-54-23](https://user-images.githubusercontent.com/2826432/75110838-67062c00-5633-11ea-8882-9ce0ffd593af.png)

**Comment by robertleeplummerjr** [comment] 2020-02-23 12:34
> ![image](https://user-images.githubusercontent.com/20304972/75102456-83618480-55b1-11ea-8871-0a8d231c65dd.png)
> Works great!
> Should the opacity be also variable? or could it be passed to color in the function as rgba?

I believe this is going to be much harder because of how the layers are drawn, at least on a line by line basis.  They are all linked within a single line instance.  However, if it were to apply to all of the lines, I imagine it wouldn't be that difficult.


>This works beautifully now!

I'll go ahead and release it.

**Closed by robertleeplummerjr** 2020-02-23 12:34 UTC
